title: Arnav Dutta
description: Portfolio of projects and reports
author: Arnav Dutta
url: "https://404arnavdutta.github.io"
baseurl: "" # leave empty unless your site is in a subfolder

# Theme
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

# Minimal Mistakes settings
minimal_mistakes_skin: "dark"  # try "default", "dark", "air", "contrast", etc.

# Social links
social:
  type: "Person"
  name: "Arnav Dutta"
  links:
    - "https://github.com/404ArnavDutta"
    - "https://www.linkedin.com/in/arnav404/"
    - "mailto:your@email.com"  # optional

# Navigation
header_pages:
  - index.md
  - projects/index.md
  - reports/index.md
