title: Arnav Dutta
description: Portfolio of projects and reports
theme: minima
plugins:
  - jekyll-seo-tag

# Site settings
author: Arnav Dutta
url: "https://404arnavdutta.github.io"
baseurl: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Navigation (minima theme)
minima:
  social_links:
    - { platform: github,  user_url: "https://404arnavdutta.github.io" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/arnav404/" }
